services:
  mysql:
    image: mysql:8.0
    container_name: graphql-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: graphql_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - graphql-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ppassword",
        ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: graphql-backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: graphql_db
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - graphql-network

volumes:
  mysql_data:

networks:
  graphql-network:
    driver: bridge
